# Generated by Django 2.2.13 on 2020-06-21 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_repo', models.CharField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Name Repo')),
                ('owner', models.CharField(max_length=80, verbose_name='Creator Repo')),
                ('description', models.TextField(blank=True, null=True)),
                ('in_github', models.BooleanField(default=False, verbose_name='Is in Github')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60, verbose_name='Author Repo')),
                ('title', models.CharField(max_length=80, verbose_name='Title PR')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Close'), ('M', 'Merged')], max_length=1)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getHorario', to='gitpy.Repo')),
            ],
        ),
    ]
